import '../models/hudl_film.dart';
import '../models/user.dart';
import '../models/player.dart';
import '../models/game.dart';
import '../models/announcement.dart';
import '../models/coach.dart';
import '../models/max_entry.dart';
import '../models/workout.dart';
import '../models/calendar_event.dart';

/// Static demo data used for offline/development mode and as fallback
/// when Firebase is not initialized or the user is not authenticated.
class DemoData {
  DemoData._();

  // ── User ──────────────────────────────────────────────────────────

  static final AppUser user = AppUser(
    uid: 'demo_user',
    username: 'mcoleman',
    email: 'mcoleman@mvhs.example.com',
    role: UserRole.player,
    linkedPlayerId: 'demo_player',
    displayName: 'Marcus Coleman',
    mustChangePassword: false,
    mfaComplete: true,
    onboardingSurveyComplete: true,
    createdAt: DateTime(2025, 1, 15),
  );

  static final AppUser masterAdmin = AppUser(
    uid: 'master_admin',
    username: 'mark',
    email: 'mark@missionfootball.com',
    role: UserRole.admin,
    displayName: 'Mark Coleman',
    mustChangePassword: false,
    mfaComplete: true,
    onboardingSurveyComplete: true,
    createdAt: DateTime(2025, 1, 1),
  );

  // ── Player ────────────────────────────────────────────────────────

  static final Player player = Player(
    id: 'demo_player',
    firstName: 'Marcus',
    lastName: 'Coleman',
    grade: 11,
    position: 'QB',
    jerseyNumber: 7,
    team: 'varsity',
    height: "6'1\"",
    weight: 185,
    athleticClearance: 'cleared',
    updatedAt: DateTime(2025, 8, 1),
  );

  // ── Roster (69 real players from 2026-2027 roster) ──────────────

  static final List<Player> roster = [
    Player(
      id: 'roster_001',
      firstName: 'Anthony',
      lastName: 'Ajaltouni',
      grade: 11,
      position: 'DB',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'jajaltouni@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_002',
      firstName: 'Ethan',
      lastName: 'Bailey',
      grade: 11,
      position: 'OL/DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_003',
      firstName: 'Frank',
      lastName: 'Baldwin',
      grade: 11,
      position: 'WR',
      jerseyNumber: 42,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_004',
      firstName: 'Isaiah',
      lastName: 'Bird',
      grade: 11,
      position: 'RB',
      jerseyNumber: 8,
      team: 'varsity',
      sizes: {'top': 'SM', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'jbird44442@gmail.com; jennaeb88@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_005',
      firstName: 'Jeremy (J-J)',
      lastName: 'Bonhomme',
      grade: 11,
      position: 'WR',
      jerseyNumber: 17,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_006',
      firstName: 'Brady',
      lastName: 'Bowman',
      grade: 11,
      position: 'LB',
      jerseyNumber: 9,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_007',
      firstName: 'Ryder',
      lastName: 'Brown',
      grade: 11,
      position: 'DB',
      jerseyNumber: 15,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_008',
      firstName: 'Colin',
      lastName: 'Burke',
      grade: 11,
      position: 'DB',
      jerseyNumber: 21,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_009',
      firstName: 'Noah',
      lastName: 'Carreon',
      grade: 11,
      position: 'RB',
      jerseyNumber: 25,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'cheriecarreon3@yahoo.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_010',
      firstName: 'Caden',
      lastName: 'Culver',
      grade: 11,
      position: 'DB',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_011',
      firstName: 'Davonte',
      lastName: 'Curtis',
      grade: 11,
      position: 'RB',
      jerseyNumber: 7,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_012',
      firstName: 'Matthew',
      lastName: 'Dalhover',
      grade: 11,
      position: 'LB',
      jerseyNumber: 24,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'briandalhover@yahoo.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_013',
      firstName: 'Max',
      lastName: 'Davidson',
      grade: 11,
      position: 'OL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'jtmdavidson@gmail.com; wethreesaints@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_014',
      firstName: 'Kole',
      lastName: 'Davis',
      grade: 11,
      position: 'TE/DE',
      jerseyNumber: 15,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'XL'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'edavis@insanum.com; kad@kathiedavis.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_015',
      firstName: 'Ethan',
      lastName: 'Esmailian',
      grade: 11,
      position: 'QB',
      jerseyNumber: 17,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_016',
      firstName: 'Luke',
      lastName: 'Fahey',
      grade: 11,
      position: 'QB',
      jerseyNumber: 3,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'XL'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_017',
      firstName: 'Dylan',
      lastName: 'Felli',
      grade: 11,
      position: 'OL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'gregfelli@yahoo.com; kris10_hitcat@yahoo.com; thefellihouse@yahoo.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_018',
      firstName: 'Inigo (Iggy)',
      lastName: 'Flameno',
      grade: 11,
      position: 'DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_019',
      firstName: 'Zack',
      lastName: 'Foeldi',
      grade: 11,
      position: 'DB',
      jerseyNumber: 31,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_020',
      firstName: 'Gannon',
      lastName: 'Geldermann',
      grade: 11,
      position: 'DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'darceygeldermann@gmail.com; matt.geldermann@icloud.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_021',
      firstName: 'Kyle',
      lastName: 'Gerrish',
      grade: 11,
      position: 'DL/OL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'mlgerrish@cox.net; lgerrish44@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_022',
      firstName: 'Cash',
      lastName: 'Gervase',
      grade: 11,
      position: 'LB',
      jerseyNumber: 2,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'joseph0464@hotmail.com; mlarson@ssrfg.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_023',
      firstName: 'Triston',
      lastName: 'Gin Jr',
      grade: 11,
      position: 'DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_024',
      firstName: 'Luis',
      lastName: 'Gonzalez',
      grade: 11,
      position: 'OL/DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_025',
      firstName: 'Isaac',
      lastName: 'Harrison',
      grade: 11,
      position: 'DB',
      jerseyNumber: 10,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_026',
      firstName: 'Tyler',
      lastName: 'Hawksford',
      grade: 11,
      position: 'WR',
      jerseyNumber: 10,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'peggyhawksford@gmail.com; riverhawksford@yahoo.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_027',
      firstName: 'Charles',
      lastName: 'Hazen',
      grade: 11,
      position: 'WR',
      jerseyNumber: 4,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_028',
      firstName: 'Jordan',
      lastName: 'Hicks',
      grade: 11,
      position: 'DB',
      jerseyNumber: 11,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'danahickz25@gmail.com; levarh704@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_029',
      firstName: 'JD',
      lastName: 'Hill',
      grade: 11,
      position: 'DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_030',
      firstName: 'Michael',
      lastName: 'Ibarra',
      grade: 11,
      position: 'OL',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_031',
      firstName: 'Jacob',
      lastName: 'Infante',
      grade: 11,
      position: 'OL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'lisainfante316@gmail.com; pjinfante1210@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_032',
      firstName: 'William',
      lastName: 'Ingham',
      grade: 11,
      position: 'LB',
      jerseyNumber: 16,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'jeffrey.ingham@gmail.com; kirsteningham@mac.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_033',
      firstName: 'Tyler',
      lastName: 'Johnson',
      grade: 11,
      position: 'OL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'c_picha@yahoo.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_034',
      firstName: 'Jeron',
      lastName: 'Jones',
      grade: 11,
      position: 'DB/WR',
      jerseyNumber: 4,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_035',
      firstName: 'Jack',
      lastName: 'Junker',
      grade: 11,
      position: 'WR',
      jerseyNumber: 10,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'david.junker@gmail.com; kelli.junker@mac.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_036',
      firstName: 'Luke',
      lastName: 'Karby',
      grade: 11,
      position: 'WR',
      jerseyNumber: 1,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'alexak1978@hotmail.com; mkarby1966@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_037',
      firstName: 'Hayden',
      lastName: 'Koo',
      grade: 11,
      position: 'WR',
      jerseyNumber: 11,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_038',
      firstName: 'Sean',
      lastName: 'Lander',
      grade: 11,
      position: 'WR',
      jerseyNumber: 21,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_039',
      firstName: 'Thomas',
      lastName: 'Lander',
      grade: 11,
      position: 'OL/DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_040',
      firstName: 'Myles',
      lastName: 'Lassiter',
      grade: 11,
      position: 'DB',
      jerseyNumber: 20,
      team: 'varsity',
      sizes: {'top': 'SM', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'kgreen2407@gmail.com; terry3759@gmail.com; glennlassiter2@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_041',
      firstName: 'Noah',
      lastName: 'Lee',
      grade: 11,
      position: 'OL/DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'doctorjay337@gmail.com; phillylee46@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_042',
      firstName: 'Bryan',
      lastName: 'Lujano',
      grade: 11,
      position: 'TE/LB',
      jerseyNumber: 23,
      team: 'varsity',
      sizes: {'top': 'XL', 'bottom': 'XL'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_043',
      firstName: 'Jaden',
      lastName: 'Lukin',
      grade: 11,
      position: 'LB',
      jerseyNumber: 8,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_044',
      firstName: 'Max',
      lastName: 'Markofski',
      grade: 11,
      position: 'WR/LB',
      jerseyNumber: 11,
      team: 'varsity',
      sizes: {'top': 'XL', 'bottom': 'XL'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'markofskibeth@gmail.com; swmarkofski@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_045',
      firstName: 'Baxter',
      lastName: 'Middagh',
      grade: 11,
      position: 'OL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'middaghd@gmail.com; emiddagh@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_046',
      firstName: 'Jack',
      lastName: 'Miller',
      grade: 11,
      position: 'OL',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_047',
      firstName: 'Dallas',
      lastName: 'Miller',
      grade: 11,
      position: 'RB',
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_048',
      firstName: 'Isaiah',
      lastName: 'Murguia',
      grade: 11,
      position: 'K/P',
      jerseyNumber: 25,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_049',
      firstName: 'Kane',
      lastName: 'Nolte',
      grade: 11,
      position: 'DL',
      jerseyNumber: 44,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'XL'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_050',
      firstName: 'Jacob',
      lastName: 'Pelayo',
      grade: 11,
      position: 'OL',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_051',
      firstName: 'Cash',
      lastName: 'Perry',
      grade: 11,
      position: 'DB',
      jerseyNumber: 30,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_052',
      firstName: 'Tristan (L-J)',
      lastName: 'Pierce',
      grade: 11,
      position: 'DB/WR',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_053',
      firstName: 'Troy',
      lastName: 'Ramirez',
      grade: 11,
      position: 'DB',
      jerseyNumber: 21,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'jorge123@mac.com; ramirezfamilia42@yahoo.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_054',
      firstName: 'Jojo',
      lastName: 'Reed',
      grade: 11,
      position: 'DB',
      team: 'varsity',
      sizes: {'top': 'SM', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'reedanielle@gmail.com; odell.reed@yahoo.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_055',
      firstName: 'Jaydon',
      lastName: 'Riggio',
      grade: 11,
      position: 'DE',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_056',
      firstName: 'Ashton',
      lastName: 'Robertson',
      grade: 11,
      position: 'LB',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_057',
      firstName: 'Noah',
      lastName: 'Rodriguez',
      grade: 11,
      position: 'DB',
      jerseyNumber: 7,
      team: 'varsity',
      sizes: {'top': 'SM', 'bottom': 'SM'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'thebest3boys@gmail.com; ernestofrodriguez47@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_058',
      firstName: 'Jackson',
      lastName: 'Rogers',
      grade: 11,
      position: 'OL/DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'keriemiddagh@hotmail.com; rrogers122@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_059',
      firstName: 'Tanner',
      lastName: 'Sauer',
      grade: 11,
      position: 'DL',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'robertmsauer13@gmail.com; tamaralsauer@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_060',
      firstName: 'Aidan',
      lastName: 'Smith',
      grade: 11,
      position: 'DB',
      jerseyNumber: 22,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_061',
      firstName: 'Vance',
      lastName: 'Spafford',
      grade: 11,
      position: 'WR',
      jerseyNumber: 13,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_062',
      firstName: 'Caleb',
      lastName: 'Sylvia',
      grade: 11,
      position: 'K/P',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'mandysylvia@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_063',
      firstName: 'Will',
      lastName: 'Taylor',
      grade: 11,
      position: 'RB',
      jerseyNumber: 28,
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_064',
      firstName: 'Micah',
      lastName: 'Thompson',
      grade: 11,
      position: 'DE',
      team: 'varsity',
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_065',
      firstName: 'Sawyer',
      lastName: 'Thomson',
      grade: 11,
      position: 'WR/DB',
      jerseyNumber: 23,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_066',
      firstName: 'Carson',
      lastName: 'Vandermade',
      grade: 11,
      position: 'WR/DB',
      jerseyNumber: 6,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'avandermade@icloud.com; tracivrn@icloud.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_067',
      firstName: 'Bryce',
      lastName: 'Warner',
      grade: 11,
      position: 'LB',
      team: 'varsity',
      sizes: {'top': 'LG', 'bottom': 'LG'},
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'awellema@hotmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_068',
      firstName: 'Briggs',
      lastName: 'Weber',
      grade: 11,
      position: 'DE',
      team: 'varsity',
      athleticClearance: 'cleared',
      parentContact: const ParentContact(
        name: '',
        email: 'braden.weber@bsci.com; keneshaweber@gmail.com',
        phone: '',
      ),
      updatedAt: DateTime(2025, 8, 1),
    ),
    Player(
      id: 'roster_069',
      firstName: 'Kollin (K-J)',
      lastName: 'Woodbury',
      grade: 11,
      position: 'WR/DB',
      jerseyNumber: 6,
      team: 'varsity',
      sizes: {'top': 'MD', 'bottom': 'MD'},
      athleticClearance: 'cleared',
      updatedAt: DateTime(2025, 8, 1),
    ),
  ];

  // ── Games (2025 Varsity Season) ───────────────────────────────────

  static final List<Game> games = [
    // Week 0 - Scrimmage (played)
    Game(
      id: 'game_001',
      season: '2025',
      week: 0,
      date: DateTime(2025, 8, 22),
      opponent: 'Mission Viejo JV',
      location: 'home',
      time: '5:00 PM',
      level: 'varsity',
      result: const GameResult(mvScore: 28, oppScore: 7, win: true),
      notes: 'Scrimmage',
    ),
    // Week 1 (played)
    Game(
      id: 'game_002',
      season: '2025',
      week: 1,
      date: DateTime(2025, 8, 29),
      opponent: 'El Toro Chargers',
      location: 'away',
      time: '7:00 PM',
      level: 'varsity',
      result: const GameResult(mvScore: 35, oppScore: 14, win: true),
    ),
    // Week 2 (played)
    Game(
      id: 'game_003',
      season: '2025',
      week: 2,
      date: DateTime(2025, 9, 5),
      opponent: 'Tesoro Titans',
      location: 'home',
      time: '7:00 PM',
      level: 'varsity',
      result: const GameResult(mvScore: 21, oppScore: 24, win: false),
    ),
    // Week 3 (played)
    Game(
      id: 'game_004',
      season: '2025',
      week: 3,
      date: DateTime(2025, 9, 12),
      opponent: 'Dana Hills Dolphins',
      location: 'away',
      time: '7:00 PM',
      level: 'varsity',
      result: const GameResult(mvScore: 31, oppScore: 17, win: true),
    ),
    // Week 4 (played)
    Game(
      id: 'game_005',
      season: '2025',
      week: 4,
      date: DateTime(2025, 9, 19),
      opponent: 'San Clemente Tritons',
      location: 'home',
      time: '7:00 PM',
      level: 'varsity',
      result: const GameResult(mvScore: 14, oppScore: 21, win: false),
    ),
    // Week 5 (played)
    Game(
      id: 'game_006',
      season: '2025',
      week: 5,
      date: DateTime(2025, 9, 26),
      opponent: 'San Juan Hills Stallions',
      location: 'away',
      time: '7:00 PM',
      level: 'varsity',
      result: const GameResult(mvScore: 42, oppScore: 28, win: true),
    ),
    // Week 6 (played)
    Game(
      id: 'game_007',
      season: '2025',
      week: 6,
      date: DateTime(2025, 10, 3),
      opponent: 'Capistrano Valley Cougars',
      location: 'home',
      time: '7:00 PM',
      level: 'varsity',
      result: const GameResult(mvScore: 38, oppScore: 10, win: true),
    ),
    // Week 7 (upcoming)
    Game(
      id: 'game_008',
      season: '2025',
      week: 7,
      date: DateTime(2025, 10, 10),
      opponent: 'Laguna Hills Hawks',
      location: 'away',
      time: '7:00 PM',
      level: 'varsity',
    ),
    // Week 8 (upcoming)
    Game(
      id: 'game_009',
      season: '2025',
      week: 8,
      date: DateTime(2025, 10, 17),
      opponent: 'Aliso Niguel Wolverines',
      location: 'home',
      time: '7:00 PM',
      level: 'varsity',
    ),
    // Week 9 (upcoming)
    Game(
      id: 'game_010',
      season: '2025',
      week: 9,
      date: DateTime(2025, 10, 24),
      opponent: 'Trabuco Hills Mustangs',
      location: 'away',
      time: '7:00 PM',
      level: 'varsity',
    ),
  ];

  // ── Announcements ─────────────────────────────────────────────────

  static final List<Announcement> announcements = [
    Announcement(
      id: 'ann_001',
      title: 'Spring Ball Dates Announced',
      body:
          'Spring ball will run from March 10 through April 18. '
          'Practice is Monday through Thursday, 3:30-5:30 PM. '
          'Full pads start Week 2. See Coach Rivera for details.',
      author: 'Coach Rivera',
      priority: 'high',
      createdAt: DateTime(2025, 2, 20),
    ),
    Announcement(
      id: 'ann_002',
      title: 'Summer Conditioning Schedule',
      body:
          'Summer conditioning begins June 9. Sessions run 7:00-9:00 AM '
          'Monday through Friday. Bring cleats, a water bottle, and a great '
          'attitude. Attendance is tracked and expected.',
      author: 'Coach Thompson',
      createdAt: DateTime(2025, 2, 25),
    ),
    Announcement(
      id: 'ann_003',
      title: 'Team Photo Day - March 15',
      body:
          'Team and individual photos will be taken on Saturday, March 15 '
          'at 9:00 AM on the main field. Wear full home jersey. '
          'Order forms will be sent home next week.',
      author: 'Coach Rivera',
      createdAt: DateTime(2025, 3, 1),
    ),
  ];

  // ── Coaches ───────────────────────────────────────────────────────

  static const List<Coach> coaches = [
    Coach(
      id: 'coach_001',
      firstName: 'David',
      lastName: 'Rivera',
      title: 'Head Coach',
      positionGroup: 'Program',
      email: 'drivera@mvhs.example.com',
      phone: '(949) 555-0101',
    ),
    Coach(
      id: 'coach_002',
      firstName: 'Mike',
      lastName: 'Thompson',
      title: 'Offensive Coordinator',
      positionGroup: 'Offense',
      email: 'mthompson@mvhs.example.com',
    ),
    Coach(
      id: 'coach_003',
      firstName: 'James',
      lastName: 'Washington',
      title: 'Defensive Coordinator',
      positionGroup: 'Defense',
      email: 'jwashington@mvhs.example.com',
    ),
    Coach(
      id: 'coach_004',
      firstName: 'Carlos',
      lastName: 'Mendez',
      title: 'Offensive Line Coach',
      positionGroup: 'OL',
      email: 'cmendez@mvhs.example.com',
    ),
    Coach(
      id: 'coach_005',
      firstName: 'Brian',
      lastName: 'Park',
      title: 'Defensive Backs Coach',
      positionGroup: 'DB',
      email: 'bpark@mvhs.example.com',
    ),
  ];

  // ── Max Entries (progression over time for HS QB) ─────────────────

  static final List<MaxEntry> maxEntries = [
    // Fall baseline
    MaxEntry(
      date: DateTime(2024, 8, 15),
      type: 'Fall Baseline',
      clean: 155,
      squat: 255,
      bench: 175,
      incline: 155,
      total: 740,
      bodyWeight: 178,
    ),
    // Winter test
    MaxEntry(
      date: DateTime(2025, 1, 10),
      type: 'Winter Test',
      clean: 170,
      squat: 275,
      bench: 190,
      incline: 165,
      total: 800,
      bodyWeight: 182,
    ),
    // Spring test
    MaxEntry(
      date: DateTime(2025, 3, 1),
      type: 'Spring Test',
      clean: 180,
      squat: 295,
      bench: 200,
      incline: 175,
      total: 850,
      bodyWeight: 185,
    ),
  ];

  // ── Workout Program ───────────────────────────────────────────────

  static const WorkoutProgram workout = WorkoutProgram(
    id: 'workout_spring_p2',
    phaseName: 'Spring Phase 2',
    exercises: [
      Exercise(
        name: 'Back Squat',
        sets: 4,
        reps: '5',
        percentOfMax: 0.80,
        liftReference: 'squat',
      ),
      Exercise(
        name: 'Bench Press',
        sets: 4,
        reps: '5',
        percentOfMax: 0.80,
        liftReference: 'bench',
      ),
      Exercise(
        name: 'Power Clean',
        sets: 3,
        reps: '3',
        percentOfMax: 0.75,
        liftReference: 'clean',
      ),
      Exercise(
        name: 'Incline DB Press',
        sets: 3,
        reps: '8',
        notes: 'Use dumbbells, controlled tempo',
      ),
      Exercise(
        name: 'Romanian Deadlift',
        sets: 3,
        reps: '8',
        notes: 'Hamstring focus, slow eccentric',
      ),
      Exercise(
        name: 'Pull-Ups',
        sets: 3,
        reps: 'Max',
        notes: 'Weighted if bodyweight > 12 reps',
      ),
    ],
  );

  // ── Calendar Events ───────────────────────────────────────────────

  static final List<CalendarEvent> calendarEvents = [
    CalendarEvent(
      id: 'cal_001',
      date: DateTime(2025, 3, 10),
      title: 'Spring Ball Begins',
      description: 'First day of spring football practice. Helmets and shorts.',
      phase: 'Spring Ball',
      timeRange: '3:30 PM - 5:30 PM',
      level: 'all',
    ),
    CalendarEvent(
      id: 'cal_002',
      date: DateTime(2025, 3, 15),
      title: 'Team Photo Day',
      description: 'Team and individual photos on main field. Full home jersey.',
      phase: 'Spring Ball',
      timeRange: '9:00 AM - 12:00 PM',
      level: 'all',
    ),
    CalendarEvent(
      id: 'cal_003',
      date: DateTime(2025, 3, 22),
      title: 'Spring Max Testing',
      description: 'Full max testing day - squat, bench, clean, incline.',
      phase: 'Spring Ball',
      timeRange: '3:30 PM - 5:30 PM',
      level: 'all',
    ),
    CalendarEvent(
      id: 'cal_004',
      date: DateTime(2025, 4, 5),
      title: 'Parent Meeting',
      description:
          'Mandatory parent meeting in the MVHS auditorium. Season expectations, '
          'fundraising, and summer schedule.',
      phase: 'Spring Ball',
      timeRange: '6:00 PM - 7:30 PM',
      level: 'all',
    ),
    CalendarEvent(
      id: 'cal_005',
      date: DateTime(2025, 4, 18),
      title: 'Spring Game',
      description:
          'Intra-squad spring game. Offense vs defense. Family and friends welcome.',
      phase: 'Spring Ball',
      timeRange: '6:00 PM - 8:00 PM',
      allDay: false,
      level: 'varsity',
    ),
  ];


  // ── Hudl Game Films ─────────────────────────────────────────────

  static final List<HudlFilm> hudlFilms = [
    HudlFilm(
      id: 'film_001',
      gameId: 'game_002',
      opponent: 'El Toro Chargers',
      gameDate: DateTime(2025, 8, 29),
      season: '2025',
      level: 'varsity',
      hudlVideoUrl: 'https://www.hudl.com/video/3/12345/abc001',
      hudlVideoId: 'abc001',
      totalPlays: 68,
      importedBy: 'coach_001',
      importedAt: DateTime(2025, 8, 30, 10, 15),
      status: FilmStatus.ready,
      summary: const FilmSummary(
        overview:
            'Dominant win over El Toro. Offense clicked on all cylinders with a '
            'balanced attack. Defense held opponents to under 200 total yards.',
        keyTakeaways: [
          'Run game averaged 5.8 YPC behind strong O-line play',
          'Secondary had 3 pass breakups and 1 interception',
          'Red zone efficiency was 4/5 (80%)',
        ],
        teamGrades: {
          'offense': 88.0,
          'defense': 85.5,
          'specialTeams': 76.0,
        },
      ),
    ),
    HudlFilm(
      id: 'film_002',
      gameId: 'game_003',
      opponent: 'Tesoro Titans',
      gameDate: DateTime(2025, 9, 5),
      season: '2025',
      level: 'varsity',
      hudlVideoUrl: 'https://www.hudl.com/video/3/12345/abc002',
      hudlVideoId: 'abc002',
      totalPlays: 72,
      importedBy: 'coach_001',
      importedAt: DateTime(2025, 9, 6, 9, 30),
      status: FilmStatus.ready,
      summary: const FilmSummary(
        overview:
            'Tough loss to Tesoro in a back-and-forth game. Two costly turnovers '
            'in the second half swung momentum. Defense played well but tired late.',
        keyTakeaways: [
          'Turnovers in Q3 led to 10 unanswered points',
          'Pass protection broke down on 3rd downs (3 sacks allowed)',
          'Need to clean up pre-snap penalties (4 false starts)',
        ],
        teamGrades: {
          'offense': 62.0,
          'defense': 74.5,
          'specialTeams': 70.0,
        },
      ),
    ),
    HudlFilm(
      id: 'film_003',
      gameId: 'game_004',
      opponent: 'Dana Hills Dolphins',
      gameDate: DateTime(2025, 9, 12),
      season: '2025',
      level: 'varsity',
      hudlVideoUrl: 'https://www.hudl.com/video/3/12345/abc003',
      hudlVideoId: 'abc003',
      totalPlays: 65,
      importedBy: 'coach_001',
      importedAt: DateTime(2025, 9, 13, 11, 0),
      status: FilmStatus.ready,
      summary: const FilmSummary(
        overview:
            'Bounce-back road win against Dana Hills. Strong defensive effort '
            'forced 3 turnovers. Offense found rhythm in the second half.',
        keyTakeaways: [
          'Defense forced 3 turnovers including a pick-six',
          'Second-half adjustments opened up the play-action game',
          'Rushing attack controlled clock in the 4th quarter',
        ],
        teamGrades: {
          'offense': 80.0,
          'defense': 90.0,
          'specialTeams': 82.5,
        },
      ),
    ),
  ];

  // ── Hudl Plays ────────────────────────────────────────────────────

  static final List<HudlPlay> hudlPlays = [
    // Film 1 – El Toro Chargers
    const HudlPlay(
      id: 'play_001',
      filmId: 'film_001',
      playNumber: 12,
      quarter: 1,
      downAndDistance: '1st & 10',
      yardLine: 35,
      formation: 'Shotgun Trips Right',
      playType: 'pass',
      playCall: 'Mesh Concept',
      result: 'Complete - 22 yards',
      yardsGained: 22,
      isTouchdown: false,
      taggedPlayerIds: ['demo_player', 'demo_player_02'],
      coachNote: 'Great read by QB, hit the crosser in stride.',
    ),
    const HudlPlay(
      id: 'play_002',
      filmId: 'film_001',
      playNumber: 34,
      quarter: 3,
      downAndDistance: '2nd & 5',
      yardLine: 12,
      formation: 'I-Formation Strong',
      playType: 'run',
      playCall: 'Power Right',
      result: 'Rush - 12 yards, TD',
      yardsGained: 12,
      isTouchdown: true,
      taggedPlayerIds: ['demo_player_03', 'demo_player_04'],
      coachNote: 'Pulling guard sealed the edge perfectly.',
    ),
    // Film 2 – Tesoro Titans
    const HudlPlay(
      id: 'play_003',
      filmId: 'film_002',
      playNumber: 8,
      quarter: 1,
      downAndDistance: '3rd & 7',
      yardLine: 42,
      formation: 'Shotgun Empty',
      playType: 'pass',
      playCall: 'Four Verticals',
      result: 'Complete - 38 yards, TD',
      yardsGained: 38,
      isTouchdown: true,
      taggedPlayerIds: ['demo_player', 'demo_player_02'],
      coachNote: 'Perfect deep ball. Safety bit on the play-action fake.',
    ),
    const HudlPlay(
      id: 'play_004',
      filmId: 'film_002',
      playNumber: 45,
      quarter: 3,
      downAndDistance: '2nd & 3',
      yardLine: 28,
      formation: 'Shotgun Doubles',
      playType: 'pass',
      playCall: 'Slant-Flat Combo',
      result: 'Intercepted',
      yardsGained: 0,
      isTurnover: true,
      taggedPlayerIds: ['demo_player'],
      coachNote: 'QB didn\'t see the LB dropping into the passing lane. Blitz read issue.',
    ),
    // Film 3 – Dana Hills Dolphins
    const HudlPlay(
      id: 'play_005',
      filmId: 'film_003',
      playNumber: 18,
      quarter: 2,
      downAndDistance: '1st & 10',
      yardLine: 50,
      formation: 'Pistol Wing Right',
      playType: 'run',
      playCall: 'Inside Zone Left',
      result: 'Rush - 15 yards',
      yardsGained: 15,
      taggedPlayerIds: ['demo_player_03', 'demo_player_05'],
      coachNote: 'RB hit the cutback lane hard. Great downfield block by WR.',
    ),
    const HudlPlay(
      id: 'play_006',
      filmId: 'film_003',
      playNumber: 52,
      quarter: 4,
      downAndDistance: '3rd & 8',
      yardLine: 25,
      formation: 'Shotgun Trips Left',
      playType: 'pass',
      playCall: 'Smash Concept',
      result: 'Complete - 25 yards, TD',
      yardsGained: 25,
      isTouchdown: true,
      taggedPlayerIds: ['demo_player', 'demo_player_02'],
      coachNote: 'Corner route was wide open. QB put it on the money.',
    ),
  ];

  // ── Hudl Player Stats ─────────────────────────────────────────────

  static final List<HudlPlayerStats> hudlPlayerStats = [
    // Marcus Coleman – QB – vs El Toro
    const HudlPlayerStats(
      id: 'pstat_001',
      filmId: 'film_001',
      playerId: 'demo_player',
      playerName: 'Marcus Coleman',
      position: 'QB',
      stats: {
        'completions': 18,
        'attempts': 25,
        'passingYards': 245,
        'passingTDs': 3,
        'interceptions': 0,
        'completionPct': 72.0,
        'yardsPerAttempt': 9.8,
        'rushAttempts': 4,
        'rushYards': 28,
        'qbRating': 142.5,
        'sacksTaken': 1,
      },
      overallGrade: 88.5,
      gradeLabel: 'Elite',
      strengths: [
        'Pocket awareness — consistently stepped up to avoid pressure',
        'Deep ball accuracy — 4/5 on throws over 20 yards',
        'Pre-snap reads — checked out of 3 bad plays at the line',
      ],
      areasToImprove: [
        'Tendency to lock onto first read on quick game',
        'Could improve ball placement on out-breaking routes',
      ],
      highlightPlays: [12, 23, 34, 48],
      aiAnalysis:
          'Marcus was in full command of the offense against El Toro. His '
          'pocket presence was outstanding, sliding away from pressure on '
          'multiple occasions to extend plays. The deep ball was his biggest '
          'weapon, connecting on 4 of 5 attempts over 20 yards. He also made '
          'three audible changes at the line that resulted in positive plays. '
          'Minor areas to work on include going through his full progression '
          'on quick-game concepts and tightening ball placement on out routes.',
    ),
    // Marcus Coleman – QB – vs Tesoro
    const HudlPlayerStats(
      id: 'pstat_002',
      filmId: 'film_002',
      playerId: 'demo_player',
      playerName: 'Marcus Coleman',
      position: 'QB',
      stats: {
        'completions': 15,
        'attempts': 28,
        'passingYards': 180,
        'passingTDs': 1,
        'interceptions': 2,
        'completionPct': 53.6,
        'yardsPerAttempt': 6.4,
        'rushAttempts': 6,
        'rushYards': 18,
        'qbRating': 58.3,
        'sacksTaken': 3,
      },
      overallGrade: 62.0,
      gradeLabel: 'Below Average',
      strengths: [
        'Showed toughness taking hits and staying in the pocket',
        'First-quarter TD drive was well-orchestrated (8 plays, 75 yards)',
      ],
      areasToImprove: [
        'Reading the blitz — failed to identify overload blitz on 3 sacks',
        'Ball security — both INTs came from forcing throws into coverage',
        'Need quicker release on 3-step drops to beat pressure',
        'Check-down awareness — missed open RB in the flat multiple times',
      ],
      highlightPlays: [8],
      aiAnalysis:
          'A tough night for Marcus against a blitz-heavy Tesoro defense. He '
          'struggled to identify pre-snap pressure looks, resulting in 3 sacks '
          'and multiple rushed throws. Both interceptions came when he forced '
          'the ball into tight windows under duress instead of taking the '
          'check-down. The first-quarter TD drive showed what he\'s capable of '
          'when given time, but the second half was a different story as Tesoro '
          'dialed up the pressure. Key focus areas this week: blitz recognition '
          'drills, quick-release mechanics, and check-down progression reads.',
    ),
  ];
}
